"""llm_calls cached_tokens

Revision ID: 86ba8cdd8e97
Revises: b3074aa5c807
Create Date: 2026-07-06 15:25:55.729613
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "86ba8cdd8e97"
down_revision: str | None = "b3074aa5c807"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_calls", sa.Column("cached_tokens", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_calls", "cached_tokens")
    # ### end Alembic commands ###
