"""demo sessions and llm calls

Revision ID: b3074aa5c807
Revises: faff5d463169
Create Date: 2026-07-03 11:52:32.662080
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = 'b3074aa5c807'
down_revision: str | None = 'faff5d463169'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=40), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), server_default='local', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_kind'), 'llm_calls', ['kind'], unique=False)
    op.create_index(op.f('ix_llm_calls_session_id'), 'llm_calls', ['session_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('session_id', sa.String(length=64), server_default='local', nullable=False))
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=False)
    op.add_column('holdings', sa.Column('session_id', sa.String(length=64), server_default='local', nullable=False))
    op.create_index(op.f('ix_holdings_session_id'), 'holdings', ['session_id'], unique=False)
    op.add_column('reports', sa.Column('session_id', sa.String(length=64), server_default='local', nullable=False))
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.add_column('watchlist_items', sa.Column('session_id', sa.String(length=64), server_default='local', nullable=False))
    op.create_index(op.f('ix_watchlist_items_session_id'), 'watchlist_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_session_id'), table_name='watchlist_items')
    op.drop_column('watchlist_items', 'session_id')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_column('reports', 'session_id')
    op.drop_index(op.f('ix_holdings_session_id'), table_name='holdings')
    op.drop_column('holdings', 'session_id')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'session_id')
    op.drop_index(op.f('ix_llm_calls_session_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_kind'), table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
